version: '3.8'

services:
  redscan-dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    ports:
      - "5173:5173"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://localhost:3001
      - VITE_BASE44_API_URL=${VITE_BASE44_API_URL:-https://api.base44.com}
      - VITE_APP_ENV=development
      - VITE_ENABLE_DEV_TOOLS=true
      - VITE_HOT_RELOAD=true
      - VITE_LOG_LEVEL=debug
    networks:
      - redscan-network
    stdin_open: true
    tty: true
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:5173/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  redscan-network:
    driver: bridge

volumes:
  node_modules:
